spring.application.name=Ejercicio08-Reservaciones

server.port=8080

spring.datasource.url=jdbc:postgresql://us-east-1.f18d015e-3f84-43c7-8c80-b4bd08cd62b5.aws.yugabyte.cloud:5433/yugabyte?ssl=true&sslmode=require
spring.datasource.username=admin
spring.datasource.password=kW-BXzB66PxpBzFIswHGTlgCQQt5zk
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

app.jwt.secret=uLyYLhqEaBePJhA97f3p4KI0keqj9pzyijn0j876SlW
app.jwt.expiration-ms=86400000

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
management.metrics.export.simple.enabled=true
